{% set name = "spikeinterface" %}
{% set version = "0.102.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spikeinterface-{{ version }}.tar.gz
  sha256: 241035d497c0d334f083fce5b62cdec17d9295ae114c76763033e6001d70508a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.20
    - threadpoolctl >=3.0.0
    - tqdm
    - zarr >=2.18,<3
    - python-neo >=0.14.0
    - probeinterface >=0.2.23
    - packaging

test:
  imports:
    - spikeinterface
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SpikeInterface/spikeinterface
  summary: Python toolkit for analysis, visualization, and comparison of spike sorting output
  license: MIT
  license_file: LICENSE
  doc_url: https://spikeinterface.readthedocs.io/
  dev_url: https://github.com/SpikeInterface/spikeinterface

extra:
  recipe-maintainers:
    - dhmjhu
