{% set name = "spikeinterface" %}
{% set version = "0.102.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spikeinterface-{{ version }}.tar.gz
  sha256: 7d7de7d185a8a2066c2748f5dc22d521b3c01e1e3898985f8210953d0da73d7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.20  # [py<313]
    - numpy >=2.0.0  # [py>=313]
    - threadpoolctl >=3.0.0
    - tqdm
    - zarr >=2.18,<3
    - python-neo >=0.14.0
    - probeinterface >=0.2.23
    - packaging

test:
  imports:
    - spikeinterface
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SpikeInterface/spikeinterface
  summary: Python toolkit for analysis, visualization, and comparison of spike sorting output
  license: MIT
  license_file: LICENSE
  doc_url: https://spikeinterface.readthedocs.io/
  dev_url: https://github.com/SpikeInterface/spikeinterface

extra:
  recipe-maintainers:
    - dhmjhu
